[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "structify-net"
dynamic = ["version"]
description='Network Generation with controlled structure'
readme='pypi.md'
authors = [
    { name = "Remy Cazabet", email = "remy.cazabet@gmail.com" }
]
license = "MIT"
license-files = [ "LICENSE" ]
requires-python = ">=3.10"
dependencies = [
    "networkx",
    "pandas",
    "matplotlib",
    "seaborn",
    "numpy",
    "scipy",
    "tqdm",
    "mock",
    "perlin-noise",
]

[project.urls]
Documentation = "http://structify-net.readthedocs.io"
GitHub = "https://github.com/Yquetzal/structify_net"

[dependency-groups]
dev = ["sphinx", "sphinx_rtd_theme", "pytest", "jupyterlab", "ipywidgets"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/structify_net/_version.py"

[tool.hatch.version.raw-options]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"