[build-system]
# TODO : setuptools 45 / 2020, setuptools 69 / 2024, dernier 78 / 2025
# requires = ["setuptools>=64", "setuptools-scm>=8"]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "structify-net"

# This is not the real repo with a tag yet
version = "0.9.50.post1"
description='Network Generation with controlled structure'
readme='pypi.md'
authors = [
    { name = "Remy Cazabet", email = "remy.cazabet@gmail.com" }
]
license = "MIT"
license-files = [ "LICENSE" ]
requires-python = ">=3.10"
dependencies = [
    "networkx",
    "pandas",
    "matplotlib",
    "seaborn",
    "numpy",
    "scipy",
    "tqdm",
    "mock",
    "perlin-noise",
]

[project.urls]
Documentation = "http://structify-net.readthedocs.io"
GitHub = "https://github.com/Yquetzal/structify_net"

[dependency-groups]
dev = ["sphinx", "sphinx_rtd_theme", "pytest", "jupyterlab", "ipywidgets"]

# [tool.setuptools_scm]
# version_scheme = "post-release"
# local_scheme = "no-local-version"
